version: "3.9"
services:
  db:
    image: postgres:16
    container_name: ebay_price_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ebay_price
    ports: ["5432:5432"]
    volumes: [pgdata:/var/lib/postgresql/data]
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    container_name: mlflow_ui
    command: mlflow ui --host 0.0.0.0 --port 5000
    ports: ["5000:5000"]
    volumes: ["./data/artifacts:/mlflow/artifacts"]
volumes: { pgdata: {} }
